env:
  es6: true

extends:
  - plugin:prettier/recommended
plugins:
  - prettier

rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: "all"
      printWidth: 100

overrides:
  - files: ["**/*.ts", "**/*.tsx"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json

    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
    plugins:
      - "@typescript-eslint"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowExpressions: true

  - files: ["./src/main/**"]
    env:
      node: true

  - files: ["./src/renderer/**"]
    env:
      browser: true

    parserOptions:
      ecmaFeatures:
        jsx: true
    settings:
      react:
        version: detect

    extends:
      - plugin:react/recommended
    plugins:
      - react

    rules:
      react/prop-types:
        - off
